GET http://localhost:5000/v1/lists/expensevendors

###

POST http://localhost:5000/v1/lists/expensevendors

###

GET http://localhost:5000/v1/lists/expensevendors/:id

###

DELETE http://localhost:5000/v1/lists/expensevendors/:id

###

PATCH http://localhost:5000/v1/lists/expensevendors/:id