GET http://localhost:5000/v1/lists/expensecategories

###

POST http://localhost:5000/v1/lists/expensecategories

###

GET http://localhost:5000/v1/lists/expensecategories/:id

###

DELETE http://localhost:5000/v1/lists/expensecategories/:id

###

PATCH http://localhost:5000/v1/lists/expensecategories/:id